In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
dataset =pd.read_csv("cleaned_labelled_final.csv")

In [4]:
dataset.head()

,Id,Subject,HtmlBody,body,Trail_Count,Category,Manual Label
0,02s1r00001acKkkAAE,FW: Payment Query,"Good Morning, Please could I have a response t...","good morning, please could i have a response t...",1,0,Escalation
1,02s1r00001acKkkAAE,FW: Payment Query,"Payment Query Good Morning, Thank you for your...","payment query good morning, thank you for your...",2,0,Others
2,02s1r00001blgJyAAI,FW: STATEMENT & QUERIES,Please find attached copy of statement/queries...,please find attached copy of statement/queries...,1,Vendor Statement Status,Others
3,02s1r00001blgJyAAI,FW: STATEMENT & QUERIES,STATEMENT & QUERIES Please find attached up to...,statement & queries please find attached up to...,2,Vendor Statement Status,Status
4,02s1r00001blgcRAAQ,FW: Statement from Oasis Products Vending Serv...,Statement from Oasis Products Vending Services...,statement from oasis products vending services...,1,Invoice Status,Others

In [5]:
dataset.tail()

,Id,Subject,HtmlBody,body,Trail_Count,Category,Manual Label
7084,02s1r00001ft8AiAAI,RE: YOUR LAST PAYMENT [ref:_CN-00010113:ref],"YOUR LAST PAYMENTGood morning, I have an issue...","your last paymentgood morning, i have an issue...",2,Others,Status
7085,02s1r00001ft96DAAQ,Remittance request,Good morning Thank you for your recent payment...,good morning thank you for your recent payment...,1,Others,Others
7086,02s1r00001ft9SnAAI,RE: Sub: Thank you for your request: Purchase ...,Sub: Thank you for your request: Purchase orde...,sub: thank you for your request: purchase orde...,2,Awaiting Invoice scanning,Others
7087,02s1r00001ft9SnAAI,RE: Sub: Thank you for your request: Purchase ...,Sub: Thank you for your request: Purchase orde...,sub: thank you for your request: purchase orde...,3,Awaiting Invoice scanning,Status
7088,02s1r00001ft9SnAAI,RE: Sub: Thank you for your request: Purchase ...,Purchase order number p/o number - 4521687707,purchase order number p/o number - AHD_NUMBER,5,Awaiting Invoice scanning,Others

In [6]:

dataset = dataset["HtmlBody"]

In [7]:
ds = pd.DataFrame(dataset)

In [8]:

dataset.isnull().any()

True

In [9]:
dataset.dropna(inplace=True)

In [10]:

ds.to_csv("new_file.csv")

In [11]:
from textblob import TextBlob
import nltk
# nltk.download('punkt')
# nltk.download('averaged_perceptron_tagger')

In [12]:
ds

                                               HtmlBody
0     Good Morning, Please could I have a response t...
1     Payment Query Good Morning, Thank you for your...
2     Please find attached copy of statement/queries...
3     STATEMENT & QUERIES Please find attached up to...
4     Statement from Oasis Products Vending Services...
5     FW: Statement from Oasis Products Vending Serv...
6     FW: Statement from Oasis Products Vending Serv...
7     Statement from Oasis Products Vending Services...
8     EES UK CIS deductions Hi, After speaking to Sh...
9     FW: Securitas Invoice Processed Twice In Error...
10    Securitas Invoice Processed Twice In Error Hi ...
11    Dear Sirs. Please respond with regards to the ...
12    OVERDUE INVOICE for VENDOR 70096356 Please adv...
13    problemHi Supplier number 70092339 Problem Ã¢â...
14                                      FW: CIS payment
15    CIS payment Hi Can you please solve this probl...
16    FW: Invoice 11967 from CONTROL APPLICATIONS LI...
17    Invoice 11967 from CONTROL APPLICATIONS LIMITE...
18    Invoices Vendor number -72060294 Can we know t...
19    Good Afternoon, Please see the attached email ...
20                                                  NaN
21    FW: Securitas Invoice Processed Twice In Error...
22    FW: Securitas Invoice Processed Twice In Error...
23    Securitas Invoice Processed Twice In Error Hi ...
24    FW: Payment Query [ref:_CN-00001175:ref]Hi Tea...
25    FW: Payment QueryGood Morning, Please could I ...
26    Payment Query Good Morning, Thank you for your...
27    Good Afternoon Could you please advise if the ...
28    Hello All, Please could you deal with the cust...
29    NortonÃ¢â‚¬â„¢s Outstanding Monies Avtar Can I...
...                                                 ...
7059  Statement as at 31/03/2019 [ref:_CN-00008229:r...
7060  Statement as at 31/03/2019 [ref:_CN-00008229:r...
7061  This is to be match to line #30 of PO 45248160...
7062  RE: Statement as at 31/03/2019 [ref:_CN-000082...
7063  RE: Statement as at 31/03/2019 [ref:_CN-000082...
7064  Hi, I mean you have paid too low amount and it...
7065  VL: If the invoice is rejected to the Supplier...
7066  Hi, There is no difference in the invoice, ple...
7067   FW: Payment specification [ref:_CN-00007394:ref]
7068  Payment specification [ref:_CN-00007394:ref] H...
7069  Sub: Thank you for your request: FW: INVOICE 2...
7070  Sub: Thank you for your request: FW: INVOICE 2...
7071  Can someone send me the Purchase order number ...
7072  FW: UNPAID INVOICES [ref:_CN-00010131:ref] Hi ...
7073  FW: UNPAID INVOICES [ref:_CN-00010131:ref] Hi ...
7074  FW: UNPAID INVOICES Hi Team Can you please hav...
7075  Hi there, Please refer to my previous email an...
7076  Sub: Thank you for your request: Kone Plc - in...
7077  PO# fully utilized Dear Sir/Madam Please find ...
7078  Good morning team, Many thanks for this report...
7079  RE: Remittance query [ref:_CN-00010102:ref] Hi...
7080  RE: Remittance query [ref:_CN-00010102:ref] FY...
7081  Hi Team Thanks for the info, please chase up t...
7082  Good Morning Please find attached our latest s...
7083  Hi, Many thanks for your reply.Be please advis...
7084  YOUR LAST PAYMENTGood morning, I have an issue...
7085  Good morning Thank you for your recent payment...
7086  Sub: Thank you for your request: Purchase orde...
7087  Sub: Thank you for your request: Purchase orde...
7088      Purchase order number p/o number - 4521687707

[7089 rows x 1 columns]

In [13]:
import nltk

File = open("new_file.csv", encoding="utf8") 
lines = File.read() 
sentences = nltk.sent_tokenize(lines) 
nouns = [] 

for sentence in sentences:
     for word,pos in nltk.pos_tag(nltk.word_tokenize(str(sentence))):
            if ( pos == 'NNP'):
                nouns.append(word)

In [16]:
len(nouns)

139313

In [17]:
nouns

['HtmlBody',
 'Morning',
 'Please',
 'NA50007',
 'NA50515',
 'Please',
 'Kind',
 'Regards',
 'Lorna',
 'Payment',
 'Query',
 'Good',
 'Morning',
 'Thank',
 'NA51140',
 'Ã‚Â£725.70',
 'NA50007',
 'Ã‚Â£142.99',
 'Due',
 'NA50134',
 'Ã‚Â£14.00',
 'Due',
 'NA50515',
 'Ã‚Â£725.70',
 'Due',
 'Please',
 'Kind',
 'Regards',
 'Lorna',
 'My',
 'Monday',
 'Wednesday',
 'Friday',
 'Big',
 'Yellow',
 'National',
 'Accounts',
 'Finance',
 'Big',
 'Yellow',
 'National',
 'Accounts',
 'Finance',
 'Big',
 'Yellow',
 'Group',
 'PLC',
 'T',
 'W',
 'Big',
 'Yellow',
 'Group',
 'PLC',
 'Big',
 'Yellow',
 'Group',
 'PLC',
 'England',
 'Wales',
 'No',
 '3625199',
 'Office',
 'Bridge',
 'Road',
 'Bagshot',
 'Surrey',
 'GU19',
 'Please',
 'Sue',
 'Sargeant',
 'Accounts',
 'Manager',
 'A',
 'A',
 'Ltd',
 'Maybank',
 'Road',
 'South',
 'Woodford',
 'E18',
 'Tel',
 'Fax',
 'STATEMENT',
 'QUERIES',
 'Please',
 'Please',
 'Oct.',
 'Sue',
 'Sargeant',
 'Accounts',
 'Manager',
 'A',
 'A',
 'Ltd',
 'Maybank',
 'Road',
 'South',
 'Woodford',
 'E18',
 'Tel',
 'Fax',
 'Oasis',
 'Vending',
 'Ltd',
 'KONE',
 'PLC',
 'KO572',
 'Hayley',
 'Waterman',
 'KONE',
 'Plc',
 'Expense/Accounts',
 'Assistant',
 'Direct',
 'Tel',
 'Monday',
 'Tuesday',
 'Thursday',
 'Friday',
 "Wednesday's**",
 'Global',
 'House',
 'Station',
 'Place',
 'Chertsey',
 'KT16',
 'England',
 'Internet',
 'FW',
 'Oasis',
 'Vending',
 'Ltd',
 'KONE',
 'PLC',
 'KO572',
 'Hi',
 'Sheila/Hayley',
 'Please',
 'Oasis',
 'Kind',
 'Cara',
 'FW',
 'Oasis',
 'Vending',
 'Ltd',
 'KONE',
 'PLC',
 'KO572',
 'Hi',
 'Cara',
 'Please',
 'Oasis',
 'Catherine',
 'Oasis',
 'Kr',
 'Ami',
 'Ami',
 'Jacques',
 'Construction',
 'Manager',
 'KONE',
 'Plc',
 'Bedford',
 'Road',
 'Clapham',
 'London',
 'SW4',
 'Mobile',
 'Registered',
 'Office',
 'Global',
 'House',
 'Station',
 'Place',
 'Chertsey',
 'KT16',
 'England',
 'Internet',
 'Oasis',
 'Vending',
 'Ltd',
 'KONE',
 'PLC',
 'KO572',
 'Hello',
 'Jan',
 'ALSO',
 'BE',
 'AWARE',
 'THAT',
 'OUR',
 'BANK',
 'DETAILS',
 'ARE',
 'CHANGING',
 'TO',
 'THE',
 'FOLLOWING',
 'ACCOUNT',
 'NUMBER',
 'Thank',
 'Vending',
 'Ltd',
 'EES',
 'UK',
 'CIS',
 'Hi',
 'Sheila',
 'CIS',
 'KONE',
 'September',
 'CIS',
 'Could',
 'Kind',
 'Harry',
 'Harry',
 'Middleton',
 'Office',
 'Manager',
 'Office',
 '+44',
 'Direct',
 'Dial',
 'Office',
 'Tel',
 'Fax',
 'Please',
 'Elevator',
 'Engineering',
 'UK',
 'LTD',
 'Edgemead',
 'Close',
 'Round',
 'Spinney',
 'Ind',
 'Est',
 'Northampton',
 'NN3',
 'Company',
 'Registered',
 'England',
 'No',
 'Elevator',
 'Engineering',
 'Elevator',
 'Engineering',
 'FW',
 'Securitas',
 'Invoice',
 'Twice',
 'Error',
 'Hi',
 'All',
 'Jan',
 '¢t',
 'Could',
 'Hayley',
 'Waterman',
 'KONE',
 'Plc',
 'Expense/Accounts',
 'Assistant',
 'Direct',
 'Tel',
 'Monday',
 'Tuesday',
 'Thursday',
 'Friday',
 "Wednesday's**",
 'Global',
 'House',
 'Station',
 'Place',
 'Chertsey',
 'KT16',
 'England',
 'Internet',
 'Securitas',
 'Invoice',
 'Twice',
 'Error',
 'Hi',
 'All',
 'Please',
 'MM',
 'Doc',
 '¢t',
 'Fridays',
 'Ã¢â‚¬â€œ',
 'Thanks',
 'Hayley',
 'Waterman',
 'KONE',
 'Plc',
 'Expense/Accounts',
 'Assistant',
 'Direct',
 'Tel',
 'Monday',
 'Tuesday',
 'Thursday',
 'Friday',
 "Wednesday's**",
 'Global',
 'House',
 'Station',
 'Place',
 'Chertsey',
 'KT16',
 'England',
 'Internet',
 'Dear',
 'Sirs',
 'NO',
 'CIS',
 'Jane',
 'Cook',
 'STENTOFON',
 'ZENITEL',
 'UK',
 'ZENITEL',
 'UK',
 'LTD',
 'MACK',
 'HOUSE',
 'Ã¢â‚¬Â¢',
 'GATWICK',
 'ROAD',
 'Ã¢â‚¬Â¢',
 'CRAWLEY',
 'Ã¢â‚¬Â¢',
 'WEST',
 'SUSSEX',
 'Ã¢â‚¬Â¢',
 'RH10',
 'Ã¢â‚¬Â¢',
 'UK',
 'SWITCHBOARD',
 'FAX',
 'JANE.COOK',
 '@',
 'ZENITELUK.COM',
 'Ã¢â‚¬Â¢',
 'WWW.ZENITELUK.COM',
 'OVERDUE',
 'INVOICE',
 'VENDOR',
 'Please',
 'CIS',
 'Please',
 'Jane',
 'Cook',
 'STENTOFON',
 'ZENITEL',
 'UK',
 'ZENITEL',
 'UK',
 'LTD',
 'MACK',
 'HOUSE',
 'Ã¢â‚¬Â¢',
 'GATWICK',
 'ROAD',
 'Ã¢â‚¬Â¢',
 'CRAWLEY',
 'Ã¢â‚¬Â¢',
 'WEST',
 'SUSSEX',
 'Ã¢â‚¬Â¢',
 'RH10',
 'Ã¢â‚¬Â¢',
 'UK',
 'SWITCHBOARD',
 'FAX',
 'JANE.COOK',
 '@',
 'ZENITELUK.COM',
 'Ã¢â‚¬Â¢',
 'WWW.ZENITELUK.COM',
 'Supplier',
 'Problem',
 'Ã¢â‚¬â€œ',
 'CIS',
 'Ã‚Â£20.00',
 'NOT',
 'Ã‚Â£300.00',
 'Remittance',
 'No',
 'Regards',
 'Angela',
 'MylettMersey',
 'Lift',
 'Fabrication',
 'Ltd3A',
 'Caddick',
 'RoadKnowsley',
 'Business',
 'ParkPrescotLiverpoolL34',
 'FW',
 'CIS',
 'CIS',
 'Hi',
 'Can',
 'Remittance',
 'Thursday',
 'Ã¢â‚¬â€œ',
 'BUT',
 'Ã‚Â£7,200.00',
 'Ã‚Â£100.00',
 'C',
 'S',
 'Tax',
 'Please',
 'IÃ¢â‚¬â',
 '„',
 '¢m',
 'Regards',
 'Angela',
 'MylettMersey',
 'Lift',
 'Fabrication',
 'Ltd3A',
 'Caddick',
 'RoadKnowsley',
 'Business',
 'ParkPrescotLiverpoolL34',
 'FW',
 'Invoice',
 'CONTROL',
 'APPLICATIONS',
 'LIMITED',
 'GOOD',
 'AFTERNOON',
 'October',
 '„',
 'Christmas',
 'Janet',
 'Invoice',
 'CONTROL',
 'APPLICATIONS',
 'LIMITED',
 'GOOD',
 'MORNING',
 'Ã°Å¸ËœÅ',
 'Please',
 'Vendor',
 'Can',
 'Kone028',
 'Kone050',
 '-25/10/2018',
 'Kone057',
 'Kone049',
 'Get',
 'Outlook',
 'Afternoon',
 'Please',
 'September',
 'Elaine',
 'Green',
 'Accounts',
 'Administrator',
 'ISO',
 'Company',
 'Triple',
 'A',
 'Ltd',
 'ISO',
 'Administrator',
 '@',
 'T',
 'Please',
 'TRIPLE',
 'A',
 'LIFT',
 'REFURBISHMENT',
 'N.W',
 'ATHLONE',
 'ROAD',
 'WARRINGTON',
 'CHESHIRE',
 'WA2',
 'Registered',
 'England',
 'Wales',
 'Registration',
 'Triple',
 'A',
 'Lift',
 'Refurbishment',
 'N.W',
 'Ltd',
 'FW',
 'Securitas',
 'Invoice',
 'Twice',
 'Error',
 '[',
 ']',
 'Hi',
 'Hayley',
 'KONE',
 'Helpdesk',
 'Team',
 'FW',
 'Securitas',
 'Invoice',
 'Twice',
 'ErrorHi',
 'All',
 'Jan',
 'Could',
 'Hayley',
 'WatermanKONE',
 'PlcExpense/Accounts',
 'AssistantDirect',
 'Tel',
 'Ã‚â€',
 'Monday',
 'Tuesday',
 'Thursday',
 'Friday',
 "Wednesday's**",
 'Global',
 'House',
 'Station',
 'Place',
 'Chertsey',
 'KT16',
 'England',
 'Internet',
 'Securitas',
 'Invoice',
 'Twice',
 'Error',
 'Hi',
 'All',
 'Please',
 'MM',
 'Doc',
 'Fridays',
 'Ã‚â€',
 '“',
 'Thanks',
 'Hayley',
 'WatermanKONE',
 'PlcExpense/Accounts',
 'AssistantDirect',
 'Tel',
 'Ã‚â€',
 'Monday',
 'Tuesday',
 'Thursday',
 'Friday',
 "Wednesday's**",
 'Global',
 'House',
 'Station',
 'Place',
 'Chertsey',
 'KT16',
 'England',
 'Internet',
 'FW',
 'Query',
 'Hi',
 'Team',
 'NA50007',
 'NA50515.Regards',
 'KONE',
 'Helpdesk',
 'FW',
 'QueryGood',
 'Morning',
 'Please',
 'NA50007',
 'NA50515',
 'Please',
 'Kind',
 'Regards',
 'Lorna',
 'Payment',
 'Query',
 'Good',
 'Morning',
 'Thank',
 'NA51140',
 'Ã‚Â£725.70',
 'NA50007',
 'Ã‚Â£142.99',
 'Due',
 'Ã‚Â£14.00',
 'Due',
 'Ã‚Â£725.70',
 'Due',
 'Please',
 'Kind',
 'Regards',
 'Lorna',
 'My',
 'Monday',
 'Wednesday',
 'Friday',
 'Big',
 'Yellow',
 'National',
 'Accounts',
 'Finance',
 'Big',
 'Yellow',
 'National',
 'Accounts',
 'Finance',
 'Big',
 'Yellow',
 'Group',
 'PLC',
 'T',
 'W',
 'Big',
 'Yellow',
 'Group',
 'PLC',
 'Yellow',
 'Group',
 'PLC',
 'England',
 'Wales',
 'No',
 '3625199',
 'Office',
 'Bridge',
 'Road',
 'Bagshot',
 'Surrey',
 'GU19',
 'Afternoon',
 'Could',
 'CROSSRAIL',
 'INVOICES',
 'ACCOUNT',
 'IS',
 'NOW',
 'ON',
 'STOP',
 'UNTIL',
 'PAYMENT',
 'IS',
 'MADE30.11.1819060Ã‚Â£229.80NEW',
 'BRACKEN',
 'HOUSE',
 'INVOICES',
 'Paul',
 'Kirrage',
 'Rogers06.10.1818865Ã‚Â£502.2020.10.1818894Ã‚Â£570.60THIS',
 'ACCOUNT',
 'IS',
 'NOW',
 'ON',
 'STOP',
 'UNTIL',
 'PAYMENT',
 'IS',
 'MADE30.11.1819062Ã‚Â£2,653.8015.12.1819160Ã‚Â£339.60',
 'Kind',
 'Regards',
 'Trisha',
 'MacpheeOffice',
 'Manager',
 'PA',
 'MDB',
 'C',
 'Wiles',
 'Son',
 'LtdTel',
 'Hello',
 'All',
 'Please',
 'Kind',
 'Regards',
 'Avtar',
 'Singh',
 'Front',
 'Officer',
 'KONE',
 'Plc',
 'Global',
 'House',
 'Station',
 'Place',
 'Fox',
 'Lane',
 'North',
 'CHERTSEY',
 'Surrey',
 'KT16',
 'Great',
 'Britain',
 'Email',
 '@',
 'kone.com',
 'Phone',
 'Customer',
 'Service',
 'Please',
 'NortonÃ¢â‚¬â',
 '„',
 '¢s',
 'Outstanding',
 'Monies',
 'Avtar',
 'Can',
 'Neil',
 'Palmer',
 'Operations',
 'Director',
 'Norton',
 'Hydraulics',
 'Ltd',
 '+44',
 '@',
 'New',
 'Address',
 'Telephone',
 'January',
 'Unit',
 'North',
 'Orbital',
 'Commercial',
 'Park',
 'AL1',
 'Query',
 'Hello',
 'Queries',
 'QUERY',
 'QUERY',
 'Kind',
 'Regards',
 'Avtar',
 'Singh',
 'Front',
 'Officer',
 'KONE',
 'Plc',
 'Global',
 'House',
 'Station',
 'Place',
 'Fox',
 'Lane',
 'North',
 'CHERTSEY',
 'Surrey',
 'KT16',
 'Great',
 'Britain',
 'Email',
 '@',
 'kone.com',
 'Phone',
 'Customer',
 'Service',
 'Please',
 'RE',
 'Hi',
 'Please',
 'Rob',
 'Please',
 'Invoice',
 'Hi',
 'Rob',
 'Please',
 'Invoice',
 'Invoice',
 'BR',
 'Wendy',
 'Anderson',
 'Tendering',
 'Contract',
 'Manager',
 'Tel',
 'Mobile',
 'Participant',
 'EGBPurchasingFL',
 '@',
 'KONE.COM',
 'FL',
 'Purchasing',
 'Department',
 'Kone',
 'PLC',
 'Worthdale',
 'House',
 'Worth',
 'Bridge',
 'Road',
 'Keighley',
 'West',
 'Yorkshire',
 'BD21',
 'Registered',
 'Office',
 'Global',
 'House',
 'Station',
 'Place',
 'Chertsey',
 'KT16',
 'England',
 'Internet',
 'Re',
 'Morning',
 'Unpaid',
 'Could',
 'Rob',
 'Chantrell',
 'Jan',
 'Varkala',
 'Sandhya',
 '<',
 '@',
 'kone.com',
 '>',
 'Hi',
 'Greetings',
 'Please',
 'UK',
 'HD',
 'Team',
 'RE',
 'Hi',
 'Invoice',
 'Please',
 'Wendy',
 'Anderson',
 'Tendering',
 'Contract',
 'Manager',
 'Tel',
 'Mobile',
 'Participant',
 'EGBPurchasingFL',
 '@',
 'KONE.COM',
 'FL',
 'Purchasing',
 'Department',
 'Kone',
 'PLC',
 'Worthdale',
 'House',
 'Worth',
 'Bridge',
 'Road',
 'Keighley',
 'West',
 'Yorkshire',
 'BD21',
 'Registered',
 'Office',
 'Global',
 'House',
 'Station',
 'Place',
 'Chertsey',
 'KT16',
 'England',
 'Internet',
 'RE',
 'Dear',
 'Please',
 'Invoice',
 'GP',
 'Comments',
 'Please',
 'Paid',
 'Thank',
 'KOU',
 'Queries',
 'Wendy',
 'Could',
 'Rob',
 'Chantrell',
 'FW',
 'Limited-',
 'Kone',
 'PLC',
 'De',
 'Daniela',
 'Aciobanita',
 'Trimis',
 'August',
 'CÃ',
 '„',
 'Æ',
 '’',
 '@',
 'Cc',
 '@',
 'Stefan',
 'Lipciuc',
 '<',
 '@',
 'Subiect',
 'Limited-',
 'Kone',
 'PLC',
 'Hello',
 'Please',
 'Best',
 'Daniela',
 'Aciobanita',
 'Economist',
 'Binape',
 'Elevators',
 'UK',
 'Limited',
 'Tel.fix/fax',
 'S.C.',
 'Binape',
 'Confidential',
 'Proprietary',
 'Information.The',
 'S.',
 'C.',
 'Binape',
 'FW',
 'Limited-',
 'Kone',
 'PLC',
 'De',
 'Daniela',
 'Aciobanita',
 'Trimis',
 'June',
 'CÃ',
 '„',
 'Æ',
 '’',
 '@',
 'kone.com',
 '@',
 'kone.com',
 '>',
 'Cc',
 '@',
 'kone.com',
 '<',
 '@',
 'kone.com',
 '>',
 'Stefan',
 'Lipciuc',
 '<',
 '@',
 'Subiect',
 'Limited-',
 'Kone',
 'PLC',
 'Hello',
 'Please',
 'Best',
 'Daniela',
 'Aciobanita',
 'Economist',
 'Binape',
 'Elevators',
 'UK',
 'Limited',
 'Tel.fix/fax',
 'S.C.',
 'Binape',
 'Confidential',
 'Proprietary',
 'Information.The',
 'S.',
 'C.',
 'Binape',
 'Hello',
 'Please',
 'Best',
 'Daniela',
 'Aciobanita',
 'Economist',
 'Binape',
 'Elevators',
 'UK',
 'Limited',
 'Tel.fix/fax',
 'S.C.',
 'Binape',
 'Confidential',
 'Proprietary',
 'Information.The',
 'S.',
 'C.',
 'Binape',
 'Neopost',
 'Invoice',
 'Query',
 ...]